import type { Metadata } from "next";
import "@/app/_styles/main.scss";

export const metadata: Metadata = {
  title: "Dictionary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
