import type { Metadata } from "next";
import "@/app/_styles/main.scss";
import { SearchProvider } from "../_contexts/SearchContext";
import { ThemeProvider } from "../_contexts/ThemeContext";

export const metadata: Metadata = {
  title: "Dictionary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <SearchProvider>{children}</SearchProvider>
      </ThemeProvider>
    </html>
  );
}
