import type { Metadata } from "next";
import "@/app/_styles/main.scss";
import { SearchProvider } from "../_contexts/SearchContext";

export const metadata: Metadata = {
  title: "Dictionary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body data-theme={"dark"}>
        <SearchProvider>{children}</SearchProvider>
      </body>
    </html>
  );
}
